/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import controller.DAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.chi_so_khach_hang;

/**
 *
 * @author ThinkPro
 */
public class giao_dien_tinh_toan extends javax.swing.JFrame {
private ArrayList<chi_so_khach_hang> list;/* tạo mảng danh sách khách hàng */
DefaultTableModel model;/* tạo đối tượng dữ liệu */
    /**
     * Creates new form giao_dien_tinh_toan
     */
    public giao_dien_tinh_toan() {
        initComponents();
         list = new DAO().getListchi_so_khach_hang();
        model = (DefaultTableModel) jTable1.getModel();
           showTable();
        
                
           
    }
   public void showTable(){
for(chi_so_khach_hang s: list){
        model.addRow(new Object[]{
            s.getMakh(), s.getTen(), s.getTuoi(),s.getChieu_cao(),s.getCan_nang() ,s.getBmi(),  s.getBody(), s.getCalo()
        });
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tinh = new javax.swing.JButton();
        ho_ten = new javax.swing.JTextField();
        tuoi = new javax.swing.JTextField();
        chieu_cao = new javax.swing.JTextField();
        can_nang = new javax.swing.JTextField();
        thoat = new javax.swing.JButton();
        add = new javax.swing.JButton();
        body_fat = new javax.swing.JLabel();
        calo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bmi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        makh = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        jLabel2.setText("Họ và tên : ");

        jLabel3.setText("Độ tuổi : ");

        jLabel4.setText("Chiều cao :");

        jLabel5.setText("Cân nặng :");

        tinh.setText("Tính");
        tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhActionPerformed(evt);
            }
        });

        can_nang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can_nangActionPerformed(evt);
            }
        });

        thoat.setBackground(new java.awt.Color(255, 0, 0));
        thoat.setForeground(new java.awt.Color(51, 51, 51));
        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        add.setText("ADD ");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        body_fat.setText("% Body fat :");

        calo.setText("Calo tiêu thụ :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mã khách", "Họ Và Tên", "Tuổi", "Chiều Cao", "Cân nặng", "bmi", "Body fat", "calo tiêu thụ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bmi.setText("BMI :");

        jLabel6.setText("Mã khách Hàng :");

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(can_nang, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ho_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(chieu_cao, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(makh)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tinh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calo)
                            .addComponent(body_fat)
                            .addComponent(bmi))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(308, 308, 308)
                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ho_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(chieu_cao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(can_nang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(body_fat)
                        .addGap(18, 18, 18)
                        .addComponent(calo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bmi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinh)
                    .addComponent(add)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhActionPerformed
        // TODO add your handling code here:
        int x;
        float BMI,BF = 0;
        float BMR;
        chi_so_khach_hang s = new chi_so_khach_hang();
        s.setTuoi(Integer.parseInt(tuoi.getText()));
        s.setChieu_cao(Float.parseFloat(chieu_cao.getText()));
        s.setCan_nang(Float.parseFloat(can_nang.getText()));
        
        
        x = s.getTuoi();
        BMI = (int) (s.getCan_nang()/Math.pow(s.getChieu_cao()/100,2));
       if( 0 <= x && x <16){
           BF = (int) (1.51*BMI+0.7*x-3.6+1.4);
       } 
       if(16<=x && x<25){
       BF = (int) (1.2*BMI+0.23*x-10.8-5.4);
       }
       if(x>=25){
       BF = (int) (1.39*BMI+0.16*x-10.34-9);
       }
        s.setBody((int) BF);
        body_fat.setText("% Body fat : " + BF);
        BMR = (int) (66+(13.7*s.getCan_nang())+(5*s.getChieu_cao())-(6.8*s.getTuoi()));
        s.setCalo((int)BMR);
        calo.setText("calo tiêu thụ : " + BMR);
        bmi.setText("bmi :" +BMI);
    }//GEN-LAST:event_tinhActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int x;
        float BMI,BF = 0;
        float BMR;
        chi_so_khach_hang s = new chi_so_khach_hang();
        s.setMakh(makh.getText());
        s.setTen(ho_ten.getText());
        s.setTuoi(Integer.parseInt(tuoi.getText()));
        s.setChieu_cao(Float.parseFloat(chieu_cao.getText()));
        s.setCan_nang(Float.parseFloat(can_nang.getText()));
        
          x = s.getTuoi();
        BMI = (int) (s.getCan_nang()/Math.pow(s.getChieu_cao()/100,2));
        s.setBmi((int)BMI);
       if( 0 <= x && x <16){
           BF = (int) (1.51*BMI+0.7*x-3.6+1.4);
       } 
       if(16<=x && x<25){
       BF = (int) (1.2*BMI+0.23*x-10.8-5.4);
       }
       if(x>=25){
       BF = (int) (1.39*BMI+0.16*x-10.34-9);
       }
        s.setBody((int) BF);
        BMR = (int) (66+(13.7*s.getCan_nang())+(5*s.getChieu_cao())-(6.8*s.getTuoi()));
        s.setCalo((int)BMR);
       
     
        if(new DAO().addchi_so_khach_hang(s)){
        JOptionPane.showMessageDialog(rootPane, "them thanh cong");
           list.add(s);
       }else{
        JOptionPane.showMessageDialog(rootPane, "khong them duoc");
        }
          if(new DAO().insert_tong_hop(s)){
        JOptionPane.showMessageDialog(rootPane, "them thanh cong bang tong hop ");
           list.add(s);
       }else{
        JOptionPane.showMessageDialog(rootPane, "khong them duoc");
        }
        if(new DAO().insert_lich_an(s)){
        JOptionPane.showMessageDialog(rootPane, "them thanh cong bang lich an ");
           list.add(s);
       }else{
        JOptionPane.showMessageDialog(rootPane, "khong them duoc");
        }
        showResult();
    }//GEN-LAST:event_addActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        // TODO add your handling code here:
        new giao_dien_dang_nhap().setVisible(true); 
this.dispose();  
    }//GEN-LAST:event_thoatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      int selectedRow = jTable1.getSelectedRow();
      if(selectedRow >= 0){
      String chi_so_makh = (String) jTable1.getValueAt(selectedRow,0);
      for(chi_so_khach_hang s: list){
      if(chi_so_makh.equals(s.getMakh())){
      makh.setText(chi_so_makh);
      ho_ten.setText(s.getTen());
      tuoi.setText("" + s.getTuoi());
      chieu_cao.setText("" + s.getChieu_cao());
      can_nang.setText("" + s.getCan_nang());
      break;
      }
      }
      }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void can_nangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can_nangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_can_nangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x;
        float BMI,BF = 0;
        float BMR;
        chi_so_khach_hang s = new chi_so_khach_hang();
        s.setMakh(makh.getText());
        s.setTen(ho_ten.getText());
        s.setTuoi(Integer.parseInt(tuoi.getText()));
        s.setChieu_cao(Float.parseFloat(chieu_cao.getText()));
        s.setCan_nang(Float.parseFloat(can_nang.getText()));
        
          x = s.getTuoi();
        BMI = (int) (s.getCan_nang()/Math.pow(s.getChieu_cao()/100,2));
        s.setBmi((int)BMI);
       if( 0 <= x && x <16){
           BF = (int) (1.51*BMI+0.7*x-3.6+1.4);
       } 
       if(16<=x && x<25){
       BF = (int) (1.2*BMI+0.23*x-10.8-5.4);
       }
       if(x>=25){
       BF = (int) (1.39*BMI+0.16*x-10.34-9);
       }
        s.setBody((int) BF);
        BMR = (int) (66+(13.7*s.getCan_nang())+(5*s.getChieu_cao())-(6.8*s.getTuoi()));
        s.setCalo((int)BMR);
       
     
        if(new DAO().update_chi_so_khach_hang(s)){
        JOptionPane.showMessageDialog(rootPane, "sua thanh cong");
           list.add(s);
       }else{
        JOptionPane.showMessageDialog(rootPane, "sua khong thanh cong");
        }
          if(new DAO().update_tong_hop(s)){
        JOptionPane.showMessageDialog(rootPane, "sua thanh cong tong hop ");
           list.add(s);
       }else{
        JOptionPane.showMessageDialog(rootPane, "sua khong thanh cong tong hop");
        }
           if(new DAO().update_lich_an(s)){
        JOptionPane.showMessageDialog(rootPane, "sua thanh cong lich an ");
           list.add(s);
       }else{
        JOptionPane.showMessageDialog(rootPane, "sua khong thanh lich an");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(new DAO().delete_chi_so_khach_hang(makh.getText())){
        JOptionPane.showMessageDialog(rootPane, "xoa thanh cong");
          
       }else{
        JOptionPane.showMessageDialog(rootPane, "xoa khong thanh cong");
        }
        int i = jTable1.getSelectedRow();
        model.removeRow(i);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void showResult(){
        chi_so_khach_hang s = list.get(list.size()-1);
        model.addRow(new Object[]{
               s.getMakh(), s.getTen(), s.getTuoi(),s.getChieu_cao(),s.getCan_nang() ,s.getBmi(),  s.getBody(), s.getCalo()
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giao_dien_tinh_toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giao_dien_tinh_toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giao_dien_tinh_toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giao_dien_tinh_toan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giao_dien_tinh_toan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel bmi;
    private javax.swing.JLabel body_fat;
    private javax.swing.JLabel calo;
    private javax.swing.JTextField can_nang;
    private javax.swing.JTextField chieu_cao;
    private javax.swing.JTextField ho_ten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField makh;
    private javax.swing.JButton thoat;
    private javax.swing.JButton tinh;
    private javax.swing.JTextField tuoi;
    // End of variables declaration//GEN-END:variables

    private String parseInt(int tuoi) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String parseFloat(float chieu_cao) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String Integer(int tuoi) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
