/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import controller.DAO;
import controller.DAO_lich_an;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.chi_so_khach_hang;
import model.lich_an;

/**
 *
 * @author ThinkPro
 */
public class giao_dien_lich_an extends javax.swing.JFrame {
DAO_lich_an dao = new DAO_lich_an();
 private ArrayList<chi_so_khach_hang> listkh;
    /**
     * Creates new form giao_dien_lich_an
     */
    public giao_dien_lich_an() {
        initComponents();
       listkh = new DAO().getListchi_so_khach_hang();
    }
  public void fillTable_an1(){
 DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
  tbModel.setRowCount(0);//xoa data trong table
  for(lich_an st: dao.lich_an_1()){
  Object dataRow[] = new Object[2];
  dataRow[0] = st.getCac_chat();
  dataRow[1] = st.getPhan_tram();
  
 tbModel.addRow(dataRow);
 }
  } 
  
    public void fillTable_an2(){
 DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
  tbModel.setRowCount(0);//xoa data trong table
  for(lich_an st: dao.lich_an_2()){
  Object dataRow[] = new Object[2];
  dataRow[0] = st.getCac_chat();
  dataRow[1] = st.getPhan_tram();
  
 tbModel.addRow(dataRow);
 }
  } 
    
      public void fillTable_an3(){
 DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
  tbModel.setRowCount(0);//xoa data trong table
  for(lich_an st: dao.lich_an_3()){
  Object dataRow[] = new Object[2];
  dataRow[0] = st.getCac_chat();
  dataRow[1] = st.getPhan_tram();
  
 tbModel.addRow(dataRow);
 }
  } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nhap_mk_cho_calo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setText("Tính");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Các Chất", "% Các chất"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nhập MÃ Khách : ");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nhap_mk_cho_calo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nhap_mk_cho_calo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             lich_an s = new lich_an();
        for( chi_so_khach_hang z : listkh){
    if(nhap_mk_cho_calo.getText().compareTo(z.getMakh())==0){
     if(z.getCalo()>0 && 1500 >= z.getCalo()){
     if(new DAO_lich_an().update_lich_an3(nhap_mk_cho_calo.getText())){
        JOptionPane.showMessageDialog(rootPane, "bạn đã xếp lịch ăn 03 cho khách hàng");
           fillTable_an3();
       }else{
        JOptionPane.showMessageDialog(rootPane, "xep lich that bai");
        }
                
               
     }
     
     if(z.getCalo()>1500 && 3000 >= z.getCalo()){
         if(new DAO_lich_an().update_lich_an2(nhap_mk_cho_calo.getText())){
        JOptionPane.showMessageDialog(rootPane, "bạn đã xếp lịch ăn 02 cho khách hàng");
           fillTable_an2();
       }else{
        JOptionPane.showMessageDialog(rootPane, "xep lich that bai");
        }
         
         
               
            }
     
     if(z.getCalo()>3000){
          if(new DAO_lich_an().update_lich_an1(nhap_mk_cho_calo.getText())){
        JOptionPane.showMessageDialog(rootPane, "bạn đã xếp lịch ăn 01 cho khách hàng");
           fillTable_an1();
       }else{
        JOptionPane.showMessageDialog(rootPane, "xep lich that bai");
        }
               
            }
        
    }
       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new giao_dien_dang_nhap().setVisible(true); 
this.dispose();  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giao_dien_lich_an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giao_dien_lich_an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giao_dien_lich_an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giao_dien_lich_an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giao_dien_lich_an().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nhap_mk_cho_calo;
    // End of variables declaration//GEN-END:variables
}
